image: tiangolo/docker-with-compose:latest
services:
    - docker:dind

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - docker-compose build

deploy_web1:
    stage: deploy
    environment:
        name: staging
    when: manual
    script:
        - apk add --no-cache openssh-client bash
        - eval $(ssh-agent -s)
        - bash -c 'ssh-add <(echo "$CD_PRIVATEKEY")'
        - >
          ssh -o StrictHostKeyChecking=no root@$CD_URL "
            /snap/bin/docker-compose build
            /snap/bin/docker-compose -f docker-compose.yml down;
            /snap/bin/docker-compose -f docker-compose.yml up -d
          "

