image: tiangolo/docker-with-compose:latest

stages:
    - deploy

deploy_web1:
    stage: deploy
    environment:
        name: staging
    when: manual
    script:
        - apk add --no-cache openssh-client bash sshpass
        - eval $(ssh-agent -s)
        - >
          sshpass -p "$CD_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$CD_URL "
            cd /root/edh-pairings/;
            git pull;
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD;
            docker-compose build;
            docker-compose -f docker-compose.yml down;
            docker-compose -f docker-compose.yml up -d;
          "

deploy_heroku:
    stage: deploy
    environment:
        name: heroku_staging
    when: manual
    script:
        - git push heroku master:master
