name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:dind
        options: >-
          --privileged
          -e DOCKER_TLS_CERTDIR=""
        ports:
          - 2375:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Check Docker versions
        run: |
          docker version
          docker-compose version
      
      - name: Run Django tests
        run: |
          docker-compose up --build --exit-code-from=test --abort-on-container-exit db test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    #    Automatic deployment on master (commented out)
    # if: |
    #   github.event_name == 'workflow_dispatch'
    #   || (github.ref == 'refs/heads/master' && github.event_name == 'push')
    # manual deployment only
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: ${{ inputs.environment || 'staging' }}
      url: ${{ vars.HEROKU_APP_HOST }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        if: ${{ inputs.debug_enabled == 'true' }}
        run: |
          set -x  # Enable debug mode
        
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }} 